version: '3.1'
services:
  mysql:
    image: mysql
    #restart: unless-stopped
    environment:
        MYSQL_ROOT_PASSWORD: makes_ai
        MYSQL_DATABASE: makes_ai
        MYSQL_USER: makes_ai
        MYSQL_PASSWORD: makes_ai
    ports:
      - "3307:3306"
    volumes:
      - $HOME/Desktop/MySQL-Snippets/make_ai.sql:/make_ai.sql

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin:latest
    container_name: flask_phpmyadmin
    #restart: unless-stopped
    ports:
      - "5010:80"
    environment:
      PMA_HOST: mysql
      PMA_USER: makes_ai
      PMA_PASSWORD: makes_ai
      MYSQL_ROOT_PASSWORD: makes_ai

  web:
    env_file:
      - .env
    build:
      context: .
    container_name: mk-crud-application-service
    volumes:
      - .:/home/userapp/app/.
    ports:
      - '8000:8000'

  redis:
    image: "redis:alpine"
    container_name: mk-crud-application-redis
    command: redis-server
    ports:
      - "6379:6379"
